DROP TABLE IF EXISTS hw3_games CASCADE;
DROP TABLE IF EXISTS hw3_words CASCADE;
DROP TABLE IF EXISTS hw3_users CASCADE;

CREATE TABLE hw3_users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  pass_hash TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hw3_words (
  id SERIAL PRIMARY KEY,
  word VARCHAR(7) UNIQUE NOT NULL
);

CREATE TABLE hw3_games (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES hw3_users(id),
  word_id INTEGER NOT NULL REFERENCES hw3_words(id),
  score INTEGER NOT NULL DEFAULT 0,
  invalid_guesses INTEGER NOT NULL DEFAULT 0,
  won BOOLEAN NOT NULL DEFAULT FALSE,
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ended_at TIMESTAMP
);
